"""empty message

Revision ID: 18ac5e046971
Revises: 1af401df343c
Create Date: 2022-10-29 00:36:50.471292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ac5e046971'
down_revision = '1af401df343c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombremepresa', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa_trabajo')
    # ### end Alembic commands ###
